/**
 * The arbiter.
 *
 * This file is the market's verifier. Its keccak256 hash goes into every
 * attestation, so after a finding is publicly disclosed anyone can re-fetch the
 * attested artifact, re-run this exact code, and check that it reproduces the
 * grade the oracle signed. A lying oracle leaves a permanent, falsifiable record.
 *
 * Therefore this must be DETERMINISTIC: no clock, no randomness, no network, no
 * environment reads, and stable ordering of every output.
 *
 * Nothing in here is novel static analysis. These are the same coarse heuristics
 * that real npm supply-chain scanners fire on, which is the point: the market's
 * grading rule has to be cheap to re-run and boring enough to argue about.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import { keccak256, toHex, type Hex } from "viem";
import { VulnClass, type DetectorResult, type Signal } from "./types";
// Generated by `npm run fingerprint` from this file's own bytes. Committed so the
// deployed app can serve both the hash and the source that produced it.
import fingerprint from "./detector-fingerprint.json";

export const DETECTOR_VERSION = "bbb-npm-detector/1.0.0";

/** Hosts that legitimately appear in package metadata and scripts. */
const BENIGN_HOSTS = [
  "registry.npmjs.org",
  "npmjs.com",
  "github.com",
  "githubusercontent.com",
  "nodejs.org",
  "opencollective.com",
];

/** Demo IOC list. A production deployment would pull a real feed. */
const KNOWN_BAD_HOSTS = [
  "telemetry-cdn.xyz",
  "npm-metrics.dev",
  "pkg-analytics.top",
  "eslint-scope.now.sh",
];

const SENSITIVE_PATHS = [
  ".npmrc",
  ".ssh/id_rsa",
  ".ssh/id_ed25519",
  ".aws/credentials",
  ".config/gcloud",
  ".env",
  "Library/Keychains",
  "wallet.dat",
];

const INSTALL_HOOKS = ["preinstall", "install", "postinstall", "prepare", "prepublish"];

// ---------------------------------------------------------------- tar reading

interface TarEntry {
  path: string;
  text: string;
}

/**
 * Minimal reader for the gzipped POSIX tar that npm ships. Written out rather
 * than pulled from a dependency so that `detectorHash` covers the whole parse.
 */
export function readTarball(buf: Buffer): TarEntry[] {
  const raw = buf[0] === 0x1f && buf[1] === 0x8b ? Buffer.from(gunzipSync(buf)) : buf;
  const entries: TarEntry[] = [];
  let off = 0;
  let longName: string | null = null;

  while (off + 512 <= raw.length) {
    const header = raw.subarray(off, off + 512);
    if (header.every((b) => b === 0)) break;

    const nameField = header.subarray(0, 100).toString("utf8").replace(/\0.*$/, "");
    const prefix = header.subarray(345, 500).toString("utf8").replace(/\0.*$/, "");
    const sizeOctal = header.subarray(124, 136).toString("utf8").replace(/\0.*$/, "").trim();
    const size = parseInt(sizeOctal || "0", 8) || 0;
    const typeFlag = String.fromCharCode(header[156]);
    const blocks = Math.ceil(size / 512);
    const body = raw.subarray(off + 512, off + 512 + size);
    off += 512 + blocks * 512;

    if (typeFlag === "L") {
      // GNU long-name extension: the next header's real path lives in this body.
      longName = body.toString("utf8").replace(/\0.*$/, "");
      continue;
    }

    const path = longName ?? (prefix ? `${prefix}/${nameField}` : nameField);
    longName = null;

    // Regular files only ('0' or '\0'); skip dirs, links, pax headers.
    if (typeFlag === "0" || typeFlag === "\0") {
      entries.push({ path: normalize(path), text: body.toString("utf8") });
    }
  }

  entries.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  return entries;
}

/** npm tarballs nest everything under `package/`. Strip it for readable rule output. */
function normalize(p: string): string {
  return p.replace(/^\.?\/*/, "").replace(/^package\//, "");
}

// -------------------------------------------------------------------- rules

function truncate(s: string, n = 160): string {
  const flat = s.replace(/\s+/g, " ").trim();
  return flat.length > n ? `${flat.slice(0, n)}…` : flat;
}

function scanInstallHooks(entries: TarEntry[], push: (s: Signal) => void) {
  const pkg = entries.find((e) => e.path === "package.json");
  if (!pkg) return;
  let scripts: Record<string, string> = {};
  try {
    scripts = JSON.parse(pkg.text)?.scripts ?? {};
  } catch {
    push({
      rule: "manifest.unparseable",
      weight: 5,
      votes: VulnClass.Unknown,
      file: "package.json",
      evidence: truncate(pkg.text),
    });
    return;
  }

  for (const hook of INSTALL_HOOKS) {
    const body = scripts[hook];
    if (typeof body !== "string") continue;

    push({
      rule: "install-hook.present",
      weight: 10,
      votes: VulnClass.InstallHookExfil,
      file: `package.json#scripts.${hook}`,
      evidence: truncate(body),
    });

    if (/\b(curl|wget)\b/.test(body) || /\|\s*(ba)?sh\b/.test(body)) {
      push({
        rule: "install-hook.remote-shell",
        weight: 30,
        votes: VulnClass.InstallHookExfil,
        file: `package.json#scripts.${hook}`,
        evidence: truncate(body),
      });
    }
    if (/node\s+-e|node\s+--eval/.test(body)) {
      push({
        rule: "install-hook.inline-eval",
        weight: 25,
        votes: VulnClass.InstallHookExfil,
        file: `package.json#scripts.${hook}`,
        evidence: truncate(body),
      });
    }
    if (/(^|\s)(node|sh|bash)\s+\S*(scripts?\/)?\S*\.(js|sh)/.test(body)) {
      push({
        rule: "install-hook.runs-script",
        weight: 8,
        votes: VulnClass.InstallHookExfil,
        file: `package.json#scripts.${hook}`,
        evidence: truncate(body),
      });
    }
  }
}

function scanObfuscation(entry: TarEntry, push: (s: Signal) => void) {
  const t = entry.text;

  if (/\beval\s*\(/.test(t)) {
    push({
      rule: "obfuscation.eval",
      weight: 20,
      votes: VulnClass.ObfuscatedEval,
      file: entry.path,
      evidence: truncate(t.match(/.{0,60}\beval\s*\(.{0,60}/)?.[0] ?? "eval("),
    });
  }
  if (/new\s+Function\s*\(/.test(t)) {
    push({
      rule: "obfuscation.new-function",
      weight: 18,
      votes: VulnClass.ObfuscatedEval,
      file: entry.path,
      evidence: truncate(t.match(/.{0,60}new\s+Function\s*\(.{0,60}/)?.[0] ?? "new Function("),
    });
  }
  const b64 = t.match(/['"`][A-Za-z0-9+/]{160,}={0,2}['"`]/);
  if (b64) {
    push({
      rule: "obfuscation.long-base64",
      weight: 22,
      votes: VulnClass.ObfuscatedEval,
      file: entry.path,
      evidence: `${b64[0].length - 2} chars of base64: ${truncate(b64[0], 48)}`,
    });
  }
  if (/from\s*\(\s*['"]base64['"]\s*\)|Buffer\.from\([^)]*['"]base64['"]/.test(t)) {
    push({
      rule: "obfuscation.base64-decode",
      weight: 10,
      votes: VulnClass.ObfuscatedEval,
      file: entry.path,
      evidence: truncate(t.match(/.{0,50}base64.{0,50}/)?.[0] ?? "base64"),
    });
  }
  const charCodes = t.match(/String\.fromCharCode\(/g);
  if (charCodes && charCodes.length >= 3) {
    push({
      rule: "obfuscation.charcode-chain",
      weight: 14,
      votes: VulnClass.ObfuscatedEval,
      file: entry.path,
      evidence: `${charCodes.length} String.fromCharCode calls`,
    });
  }
  const hexEscapes = t.match(/\\x[0-9a-fA-F]{2}/g);
  if (hexEscapes && hexEscapes.length >= 40) {
    push({
      rule: "obfuscation.hex-escaped-strings",
      weight: 12,
      votes: VulnClass.ObfuscatedEval,
      file: entry.path,
      evidence: `${hexEscapes.length} hex escapes`,
    });
  }
}

function scanExfil(entry: TarEntry, push: (s: Signal) => void) {
  const t = entry.text;

  if (/require\(\s*['"]child_process['"]\s*\)|from\s+['"]child_process['"]/.test(t)) {
    push({
      rule: "exec.child-process",
      weight: 15,
      votes: VulnClass.NetworkBackdoor,
      file: entry.path,
      evidence: truncate(t.match(/.{0,40}child_process.{0,60}/)?.[0] ?? "child_process"),
    });
  }

  for (const p of SENSITIVE_PATHS) {
    // Require a boundary before the dotfile so `.env` does not match `process.env`
    // and `.aws/credentials` does not match an unrelated substring.
    const re = new RegExp(`(^|[^A-Za-z0-9])${escapeRe(p)}`);
    const m = t.match(new RegExp(`.{0,50}(^|[^A-Za-z0-9])${escapeRe(p)}.{0,40}`));
    if (re.test(t)) {
      push({
        rule: "credentials.sensitive-path-read",
        weight: 28,
        votes: VulnClass.CredentialTheft,
        file: entry.path,
        evidence: truncate(m?.[0] ?? p),
      });
    }
  }

  if (/process\.env\b/.test(t) && /(fetch\s*\(|https?\.request|axios|XMLHttpRequest|net\.connect)/.test(t)) {
    push({
      rule: "exfil.env-plus-network",
      weight: 24,
      votes: VulnClass.CredentialTheft,
      file: entry.path,
      evidence: truncate(t.match(/.{0,50}process\.env.{0,60}/)?.[0] ?? "process.env"),
    });
  }

  // Outbound hosts that are not part of normal package plumbing.
  const hosts = new Set<string>();
  for (const m of t.matchAll(/https?:\/\/([A-Za-z0-9._-]+\.[A-Za-z]{2,})/g)) hosts.add(m[1].toLowerCase());
  for (const m of t.matchAll(/\b([a-z0-9-]+(?:\.[a-z0-9-]+)*\.(?:xyz|top|tk|ru|su|now\.sh|dev))\b/g)) {
    hosts.add(m[1].toLowerCase());
  }

  for (const host of [...hosts].sort()) {
    if (KNOWN_BAD_HOSTS.some((bad) => host === bad || host.endsWith(`.${bad}`))) {
      push({
        rule: "ioc.known-bad-host",
        weight: 35,
        votes: VulnClass.NetworkBackdoor,
        file: entry.path,
        evidence: host,
      });
    } else if (!BENIGN_HOSTS.some((ok) => host === ok || host.endsWith(`.${ok}`))) {
      push({
        rule: "network.unexpected-host",
        weight: 8,
        votes: VulnClass.NetworkBackdoor,
        file: entry.path,
        evidence: host,
      });
    }
  }
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// ------------------------------------------------------------------- scoring

/** Cheap concavity so a pile of weak signals never outranks one strong one. */
function score(signals: Signal[]): number {
  const byRule = new Map<string, number>();
  for (const s of signals) {
    // A rule firing in many files counts once at full weight, then with decay.
    const seen = byRule.get(s.rule) ?? 0;
    byRule.set(s.rule, seen + s.weight / (seen === 0 ? 1 : 4));
  }
  const total = [...byRule.values()].reduce((a, b) => a + b, 0);
  return Math.min(100, Math.round(total));
}

function classify(signals: Signal[]): VulnClass {
  const tally = new Map<VulnClass, number>();
  for (const s of signals) tally.set(s.votes, (tally.get(s.votes) ?? 0) + s.weight);
  let best = VulnClass.Unknown;
  let bestWeight = -1;
  // Iterate the enum in a fixed order so ties resolve deterministically.
  for (const c of [
    VulnClass.CredentialTheft,
    VulnClass.InstallHookExfil,
    VulnClass.NetworkBackdoor,
    VulnClass.ObfuscatedEval,
    VulnClass.DependencyConfusion,
    VulnClass.Unknown,
  ]) {
    const w = tally.get(c) ?? 0;
    if (w > bestWeight) {
      best = c;
      bestWeight = w;
    }
  }
  return bestWeight <= 0 ? VulnClass.Unknown : best;
}

// -------------------------------------------------------------------- public

/** keccak256 of this file's own bytes, recorded in every attestation. */
export function detectorHash(): Hex {
  return fingerprint.detectorHash as Hex;
}

/** The exact source that produced every grade, so a third party can re-run it. */
export function detectorSource(): { source: string; detectorHash: Hex; bytes: number } {
  return {
    source: fingerprint.source,
    detectorHash: fingerprint.detectorHash as Hex,
    bytes: fingerprint.bytes,
  };
}

/** Recompute the fingerprint from source text. Used by the generator and the verifier. */
export function computeDetectorHash(source: string | Buffer): Hex {
  return keccak256(toHex(typeof source === "string" ? Buffer.from(source, "utf8") : source));
}

export function sha256Hex(buf: Buffer): Hex {
  return `0x${createHash("sha256").update(buf).digest("hex")}`;
}

const SKIP_EXT = /\.(png|jpg|jpeg|gif|webp|ico|woff2?|ttf|eot|mp4|wasm|map)$/i;

export function analyze(tarball: Buffer): DetectorResult {
  const entries = readTarball(tarball);
  const signals: Signal[] = [];
  const push = (s: Signal) => signals.push(s);

  scanInstallHooks(entries, push);

  for (const entry of entries) {
    if (SKIP_EXT.test(entry.path)) continue;
    if (entry.text.length > 512_000) continue; // bundles are out of scope for this grade
    scanObfuscation(entry, push);
    scanExfil(entry, push);
  }

  signals.sort((a, b) =>
    a.rule !== b.rule ? (a.rule < b.rule ? -1 : 1) : a.file < b.file ? -1 : a.file > b.file ? 1 : 0,
  );

  return {
    artifactHash: sha256Hex(tarball),
    signals,
    severity: score(signals),
    vulnClass: classify(signals),
    detectorHash: detectorHash(),
    detectorVersion: DETECTOR_VERSION,
  };
}

export function analyzeFile(path: string): DetectorResult {
  return analyze(readFileSync(path));
}
